
# VS image
image: Visual Studio 2017

# which branches should be used
branches:
  only:
  - master # build pull requests on master
  
force_https_clone: true
skip_tags: false
skip_non_tags: false
clone_depth: 1

# build
build_script:
- ps: ./build.ps1 -Target Build

# test
#test_script:
#- ps: ./build.ps1 -Target TestOnly


