# VS image

image: Visual Studio 2017



# which branches should be used

branches:

  only:

  - master # build pull requests on master

  

# add required nuget references

before_build:

  # add reference for Configit Nuget Server

  - ps: nuget sources Add -ApiKey 0edp0d40ga2iked1w84t8n41 -Source https://ci.appveyor.com/nuget/narenderchary892-k43q4o13cfj5/api/v2/packag -UserName NarenderChary892 -Password Neverg!veup
  

# build

build_script:

- ps: ./build.ps1 -Target Build



# test

#test_script:

#- ps: ./build.ps1 -Target TestOnly
