# VS image

image: Visual Studio 2017



# which branches should be used

branches:

  only:

  - master # build pull requests on master

  - Development # build Development



force_https_clone: true

skip_tags: false

skip_non_tags: false

clone_depth: 1



# set environment variables

environment:

  ConfigitNuGetPassword:

    secure: izpoVw2TicdHmyR345magw==

  

# add required nuget references

before_build:

  # add reference for Configit Nuget Server

  - ps: nuget sources Add -Name Configit -Source http://nuget.configit.com/nuget/Configit -UserName bob -Password $Env:ConfigitNuGetPassword

  

# build

build_script:

- ps: ./build.ps1 -Target Build



# test

#test_script:

#- ps: ./build.ps1 -Target TestOnly





    

      

