# VS image

image: Visual Studio 2017



# which branches should be used

branches:

  only:

  - master # build pull requests on master

# set environment variables



# add required nuget references

before_build:

  # add reference for Configit Nuget Server

  - ps: Install-Package NuGet.VisualStudio -Version 4.6.2
  

# build

build_script:

- ps: ./build.ps1 -Target Build



# test

#test_script:

#- ps: ./build.ps1 -Target TestOnly





    

      

